# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: RunTests
  default: true

trigger:
- main
- master

pool:
    vmImage: 'ubuntu-20.04'

jobs:
- job: RunTests
  steps:
  
  - template: azure-pipelines-test.yml  # Template reference

- job: CreateRelease
  steps:
  
  - script: |
        set -euo pipefail
        echo package chart
        cp -r . $(Agent.TempDirectory)
        cd $(Agent.TempDirectory)
        wget https://github.com/helm/chart-releaser/releases/download/v1.1.1/chart-releaser_1.1.1_linux_amd64.tar.gz
        tar -xvzf chart-releaser_1.1.1_linux_amd64.tar.gz -C ./
        ls
        sudo chmod +x ./cr
        sudo ./cr package ./hull 
        sudo ./cr upload --git-repo hull --owner vidispine --token $(GITHUBTOKEN) || true
        mkdir .cr-index
        wget https://vidispine.github.io/hull/index.yaml -O .cr-index/index.yaml
        sudo ./cr index --git-repo hull --owner vidispine --token $(GITHUBTOKEN) --charts-repo https://vidispine.github.io/hull --push 
        #sudo docker pull quay.io/helmpk/chart-releaser:v1.1.1
        #sudo docker run -v /hull:/hull -v $(Agent.TempDirectory):/tmp --entrypoint cr quay.io/helmpk/chart-releaser:v1.1.1 package /hull/hull --package-path /hull
   
