# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: RunTests
  default: false
- name: HelmVersions
  type: object
  default:
  - version: "3.0.0"
  - version: "3.2.4"
  - version: "3.4.2"

trigger:
- main
- master

pool:
    vmImage: 'ubuntu-20.04'

steps:
- script: |
      echo installing gauge
      sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 023EDB0B
      echo deb https://dl.bintray.com/gauge/gauge-deb stable main | sudo tee -a /etc/apt/sources.list
      sudo apt-get update
      sudo apt-get install gauge
      cd hull/files/test/HULL
      sudo pip install -r requirements.txt

  displayName: 'install gauge'
  condition: eq('${{ parameters.RunTests }}',true)

- ${{ each version in parameters.HelmVersions }}: # Each Helm Version
  
  - script: |
      set -euo pipefail
      echo installing helm
      wget https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
      sudo chmod +x ./get-helm-3
      sudo ./get-helm-3 --version v${{ version.version }}
      helm version
    displayName: 'install helm'
    condition: eq('${{ parameters.RunTests }}',true)

  - script: |
      set -euo pipefail
      echo starting gauge test
      ls
      cd hull/files/test/HULL
      ls
      gauge run -p -l debug specs
    displayName: 'gauge test'
    condition: eq('${{ parameters.RunTests }}',true)

- task: Docker@2
  displayName: 'Merge Registry and Repository fields to single Repository field'
  inputs:
    container: 'quay.io/helmpk/chart-releaser:v1.1.1'
    command: run
    arguments: "--entrypoint cr -v /hull:/hull $(Agent.TempDirectory):/tmp quay.io/helmpk/chart-releaser:v1.1.1 package /hull/hull --package-path /tmp"

- script: |
      set -euo pipefail
      echo package chart
      docker pull quay.io/helmpk/chart-releaser:v1.1.1
      docker run -v /hull:/hull --entrypoint "cr" quay.io/helmpk/chart-releaser:v1.1.1 package /hull/hull --package-path /hull    
  #condition: eq(variables['create_subchart'],true)