# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: RunTests
  default: true

trigger: none

pool:
    vmImage: 'ubuntu-20.04'

jobs:
- job: RunTests
  strategy:
    maxParallel: 10
    matrix:
      3_0_0:
        HelmVersion: "3.0.0"
      3_0_1:
        HelmVersion: "3.0.1"
      3_0_2:
        HelmVersion: "3.0.2"
      3_0_3:
        HelmVersion: "3.0.3"
      3_1_0:
        HelmVersion: "3.1.0"
      3_1_1:
        HelmVersion: "3.1.1"
      3_1_2:
        HelmVersion: "3.1.2"
      3_1_3:
        HelmVersion: "3.1.3"
      3_2_0:
        HelmVersion: "3.2.0"
      3_2_1:
        HelmVersion: "3.2.1"
      3_2_2:
        HelmVersion: "3.2.2"
      3_2_3:
        HelmVersion: "3.2.3"
      3_2_4:
        HelmVersion: "3.2.4"
      3_3_0:
        HelmVersion: "3.3.0"
      3_3_1:
        HelmVersion: "3.3.1"
      3_3_2:
        HelmVersion: "3.3.2"
      3_3_3:
        HelmVersion: "3.3.3"
      3_3_4:
        HelmVersion: "3.3.4"
      3_4_0:
        HelmVersion: "3.4.0"
      3_4_1:
        HelmVersion: "3.4.1"
      3_4_2:
        HelmVersion: "3.4.2"
      3_5_0:
        HelmVersion: "3.5.0"
      3_5_1:
        HelmVersion: "3.5.1"        
      3_5_2:
        HelmVersion: "3.5.2"
  steps:
  
  - template: azure-pipelines-test.yml  # Template reference
    parameters:
      HelmVersions:
      - version: $(HelmVersion)
